# permissions for end users to edit demoservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demoservices-editor-role
rules:
- apiGroups:
  - grpcdemo.example.com
  resources:
  - demoservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - grpcdemo.example.com
  resources:
  - demoservices/status
  verbs:
  - get
