apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: services.grpcdemo.example.com
spec:
  group: grpcdemo.example.com
  names:
    kind: Services
    listKind: ServicesList
    plural: services
    singular: services
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Services is the Schema for the services API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ServicesSpec defines the desired state of Services
            properties:
              services:
                description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "operator-sdk generate k8s" to regenerate code after
                  modifying this file Add custom validation using kubebuilder tags:
                  https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
                items:
                  description: Service defines the desired state of a Service
                  properties:
                    image:
                      type: string
                    limits:
                      description: Resources defines the desired resources for limits
                        and requests
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                      required:
                      - cpu
                      - memory
                      type: object
                    name:
                      type: string
                    replicas:
                      format: int32
                      type: integer
                    requests:
                      description: Resources defines the desired resources for limits
                        and requests
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                      required:
                      - cpu
                      - memory
                      type: object
                    version:
                      type: string
                  required:
                  - image
                  - limits
                  - name
                  - replicas
                  - requests
                  - version
                  type: object
                type: array
            required:
            - services
            type: object
          status:
            description: ServicesStatus defines the observed state of Services
            properties:
              services:
                description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                  of cluster Important: Run "operator-sdk generate k8s" to regenerate
                  code after modifying this file Add custom validation using kubebuilder
                  tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
                items:
                  description: ServiceStatus defines the observed state of a single
                    Service
                  properties:
                    name:
                      type: string
                    status:
                      type: string
                  required:
                  - name
                  - status
                  type: object
                type: array
            required:
            - services
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
