apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grpc-demo-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - services
  - services/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resourceNames:
  - grpc-demo-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - grpcdemo.example.com
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
